user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
    max_length: 30
  gravatar:
    size: 80
    for_user: 50
  validates:
    minimum: 6
session:
  remember_me: "1"
per_page:
  user: 20
