user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
    max_length: 30
  gravatar:
    size: 80
    for_user: 50
  validates:
    minimum: 6
session:
  remember_me: "1"
time_reset: 2
per_page:
  user: 20
  microposts: 30
micropost:
  maximum_length: 140
  gravatar_for_size: 30
picture:
  max_size: 5
